import { Plus, Trash2 } from 'lucide-react'
import { useEffect, useMemo, useState } from 'react'

import { Drawer } from '../../../components/drawer'
import { SelectField, TextField } from '../../../components/forms'
import { Button, IconButton, useToast } from '../../../components/ui'
import { createSale } from '../../../services'
import type { InventoryProduct } from '../../../types/inventory'
import type { Quotation } from '../../../types/quotation'
import type { Sale } from '../../../types/sale'

type DraftItem = { productId: string; quantity: string }
type Props = { open: boolean; businessId: string; currency: string; products: InventoryProduct[]; quotation?: Quotation | null; onClose: () => void; onSaved: (sale: Sale) => void }

export function SaleDrawer({ open, businessId, currency, products, quotation, onClose, onSaved }: Props) {
  const toast = useToast(); const [customerName, setCustomerName] = useState(''); const [customerEmail, setCustomerEmail] = useState(''); const [customerPhone, setCustomerPhone] = useState(''); const [notes, setNotes] = useState(''); const [selectedProduct, setSelectedProduct] = useState(''); const [items, setItems] = useState<DraftItem[]>([]); const [saving, setSaving] = useState(false); const [error, setError] = useState<string | null>(null)
  useEffect(() => { if (!open) return; setCustomerName(quotation?.customerName ?? 'Consumidor final'); setCustomerEmail(quotation?.customerEmail ?? ''); setCustomerPhone(quotation?.customerPhone ?? ''); setNotes(quotation?.notes ?? ''); setSelectedProduct(''); setItems(quotation?.items.map((item) => ({ productId: item.productId, quantity: String(item.quantity) })) ?? []); setError(null) }, [open, quotation])
  const formatMoney = (value: number) => new Intl.NumberFormat('es-EC', { style: 'currency', currency }).format(value)
  const selectedIds = new Set(items.map((item) => item.productId)); const availableProducts = products.filter((product) => !selectedIds.has(product.id)); const rows = useMemo(() => items.map((item) => { const product = products.find((candidate) => candidate.id === item.productId); const quotedPrice = quotation?.items.find((quoted) => quoted.productId === item.productId)?.unitPrice; return { ...item, product: product ? { ...product, salePrice: quotedPrice ?? product.salePrice } : undefined } }).filter((item): item is DraftItem & { product: InventoryProduct } => Boolean(item.product)), [items, products, quotation]); const subtotal = rows.reduce((sum, item) => sum + item.product.salePrice * (Number(item.quantity) || 0), 0); const tax = Math.round((subtotal * 0.15 + Number.EPSILON) * 100) / 100
  function addProduct() { if (!selectedProduct) return; setItems((current) => [...current, { productId: selectedProduct, quantity: '1' }]); setSelectedProduct('') }
  async function submit() { if (!customerName.trim()) return setError('Ingresa el nombre del cliente.'); if (!items.length) return setError('Agrega al menos un producto.'); if (items.some((item) => !Number.isInteger(Number(item.quantity)) || Number(item.quantity) <= 0)) return setError('Todas las cantidades deben ser enteros mayores que cero.'); try { setSaving(true); setError(null); const result = await createSale(businessId, { sourceQuotationId: quotation?.id, customerName, customerEmail, customerPhone, notes, items: items.map((item) => ({ productId: item.productId, quantity: Number(item.quantity) })) }); toast.success('Venta registrada', result.message); onSaved(result.sale); onClose() } catch (requestError) { setError(requestError instanceof Error ? requestError.message : 'No fue posible registrar la venta.') } finally { setSaving(false) } }
  return <Drawer open={open} title={quotation ? `Convertir ${quotation.number} en venta` : 'Nueva venta'} description="Puedes cambiar cantidades, quitar productos o agregar otros antes de confirmar." onClose={onClose} footer={<><Button variant="secondary" onClick={onClose}>Cancelar</Button><Button loading={saving} onClick={() => void submit()}>Confirmar venta</Button></>}><div className="quote-form"><section className="quote-form__section"><h3>Cliente</h3><TextField id="sale-customer" label="Nombre" value={customerName} required onChange={setCustomerName} /><div className="quote-form__grid"><TextField id="sale-email" label="Correo" type="email" value={customerEmail} onChange={setCustomerEmail} /><TextField id="sale-phone" label="WhatsApp" type="tel" value={customerPhone} onChange={setCustomerPhone} /></div></section><section className="quote-form__section"><h3>Productos</h3><div className="quote-add-product"><SelectField id="sale-product" label="Producto del inventario" value={selectedProduct} options={[{ value: '', label: availableProducts.length ? 'Selecciona un producto' : 'No hay más productos disponibles' }, ...availableProducts.map((product) => ({ value: product.id, label: `${product.code} · ${product.name} · ${formatMoney(product.salePrice)} · stock ${product.quantity}` }))]} onChange={setSelectedProduct} /><Button type="button" variant="secondary" icon={<Plus size={17} />} disabled={!selectedProduct} onClick={addProduct}>Agregar</Button></div>{rows.map((item) => <div className="quote-item" key={item.productId}><div><strong>{item.product.name}</strong><small>{item.product.code} · {item.product.brand} · {formatMoney(item.product.salePrice)} · disponible {item.product.quantity}</small></div><input aria-label={`Cantidad de ${item.product.name}`} type="number" min="1" max={item.product.quantity} step="1" value={item.quantity} onChange={(event) => setItems((current) => current.map((candidate) => candidate.productId === item.productId ? { ...candidate, quantity: event.target.value } : candidate))} /><strong>{formatMoney(item.product.salePrice * (Number(item.quantity) || 0))}</strong><IconButton icon={<Trash2 size={16} />} label={`Quitar ${item.product.name}`} variant="danger" onClick={() => setItems((current) => current.filter((candidate) => candidate.productId !== item.productId))} /></div>)}</section><section className="quote-form__section"><label className="quote-notes" htmlFor="sale-notes">Observaciones<textarea id="sale-notes" value={notes} maxLength={1000} rows={3} onChange={(event) => setNotes(event.target.value)} /></label><div className="quote-summary"><span>Subtotal <strong>{formatMoney(subtotal)}</strong></span><span>IVA 15% <strong>{formatMoney(tax)}</strong></span><span>Total <strong>{formatMoney(subtotal + tax)}</strong></span></div></section>{error && <p className="quote-form__error">{error}</p>}</div></Drawer>
}
