import { jsPDF } from 'jspdf'
import { autoTable } from 'jspdf-autotable'
import type { Sale } from '../../../types/sale'

const money = (value: number, currency: string) => new Intl.NumberFormat('es-EC', { style: 'currency', currency }).format(value)
const safeFilePart = (value: string) => value.normalize('NFD').replace(/[\u0300-\u036f]/g, '').toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '') || 'cliente'
async function drawLogo(document: jsPDF, logoUrl?: string | null): Promise<boolean> { if (!logoUrl) return false; try { const response = await fetch(logoUrl); if (!response.ok) return false; const contentType = response.headers.get('content-type') ?? ''; const bytes = new Uint8Array(await response.arrayBuffer()); const properties = document.getImageProperties(bytes); const ratio = Math.min(20 / properties.width, 20 / properties.height); const width = properties.width * ratio; const height = properties.height * ratio; document.setFillColor(255, 255, 255); document.roundedRect(15, 5, 24, 24, 3, 3, 'F'); document.addImage(bytes, contentType.includes('png') ? 'PNG' : 'JPEG', 17 + (20 - width) / 2, 7 + (20 - height) / 2, width, height); return true } catch { return false } }
export async function createSalePdf(sale: Sale, businessName: string, logoUrl?: string | null): Promise<{ blob: Blob; fileName: string }> {
  const document = new jsPDF({ unit: 'mm', format: 'a4' }); const pageWidth = document.internal.pageSize.getWidth(); const pageHeight = document.internal.pageSize.getHeight(); document.setFillColor(103, 68, 228); document.rect(0, 0, pageWidth, 34, 'F'); const hasLogo = await drawLogo(document, logoUrl); const businessX = hasLogo ? 45 : 15; document.setTextColor(255, 255, 255); document.setFont('helvetica', 'bold'); document.setFontSize(18); document.text(businessName, businessX, 15); document.setFontSize(10); document.setFont('helvetica', 'normal'); document.text('Factura comercial interna', businessX, 23); document.setFont('helvetica', 'bold'); document.setFontSize(15); document.text(sale.number, pageWidth - 15, 17, { align: 'right' })
  document.setTextColor(36, 30, 49); document.setFontSize(10); document.setFont('helvetica', 'bold'); document.text('Cliente', 15, 47); document.setFont('helvetica', 'normal'); document.text(sale.customerName, 15, 54); if (sale.customerEmail) document.text(sale.customerEmail, 15, 60); if (sale.customerPhone) document.text(sale.customerPhone, 15, sale.customerEmail ? 66 : 60); document.setFont('helvetica', 'bold'); document.text('Emisión', pageWidth - 62, 47); document.setFont('helvetica', 'normal'); document.text((sale.createdAt ?? new Date()).toLocaleDateString('es-EC'), pageWidth - 15, 47, { align: 'right' }); if (sale.sourceQuotationNumber) { document.setFont('helvetica', 'bold'); document.text('Cotización', pageWidth - 62, 54); document.setFont('helvetica', 'normal'); document.text(sale.sourceQuotationNumber, pageWidth - 15, 54, { align: 'right' }) }
  autoTable(document, { startY: 74, head: [['Código', 'Producto', 'Marca', 'Cantidad', 'Valor unitario', 'Valor total']], body: sale.items.map((item) => [item.code, item.name, item.brand, item.quantity, money(item.unitPrice, sale.currency), money(item.total, sale.currency)]), theme: 'plain', tableWidth: pageWidth - 30, margin: { top: 24, left: 15, right: 15, bottom: 30 }, styles: { font: 'helvetica', fontSize: 9, textColor: [58, 51, 70], cellPadding: 3.2, lineColor: [232, 228, 240], lineWidth: { bottom: 0.2 } }, headStyles: { fillColor: [103, 68, 228], textColor: [255, 255, 255], fontStyle: 'bold', lineWidth: 0 }, columnStyles: { 3: { halign: 'right' }, 4: { halign: 'right' }, 5: { halign: 'right' } }, didDrawPage: () => { document.setFontSize(8); document.setTextColor(130, 123, 142); document.text(`Generada por Inventra · Página ${document.getNumberOfPages()}`, 15, pageHeight - 12) } })
  const tableEnd = (document as jsPDF & { lastAutoTable?: { finalY: number } }).lastAutoTable?.finalY ?? 80; let totalsY = tableEnd + 9; if (totalsY > pageHeight - 62) { document.addPage(); totalsY = 28 } const labelX = pageWidth - 72; const valueX = pageWidth - 15; document.setFontSize(10); document.setTextColor(86, 78, 99); document.text('Subtotal', labelX, totalsY); document.text(money(sale.subtotal, sale.currency), valueX, totalsY, { align: 'right' }); document.text(`IVA ${(sale.taxRate * 100).toFixed(0)}%`, labelX, totalsY + 8); document.text(money(sale.tax, sale.currency), valueX, totalsY + 8, { align: 'right' }); document.setDrawColor(213, 207, 228); document.line(labelX, totalsY + 13, valueX, totalsY + 13); document.setFont('helvetica', 'bold'); document.setTextColor(36, 30, 49); document.setFontSize(13); document.text('TOTAL', labelX, totalsY + 22); document.text(money(sale.total, sale.currency), valueX, totalsY + 22, { align: 'right' }); if (sale.notes) { document.setFontSize(9); document.text('Observaciones', 15, totalsY + 9); document.setFont('helvetica', 'normal'); document.text(document.splitTextToSize(sale.notes, 105), 15, totalsY + 15) }
  return { blob: document.output('blob'), fileName: `${sale.number.toLowerCase()}-${safeFilePart(sale.customerName)}.pdf` }
}
export function downloadSalePdf(blob: Blob, fileName: string): void { const url = URL.createObjectURL(blob); const link = document.createElement('a'); link.href = url; link.download = fileName; link.click(); setTimeout(() => URL.revokeObjectURL(url), 1000) }
